### ISSUE TITLE
Beugoù

### ISSUE THREAD

**Issue by Wanibzh29** [Drouizig/displeger-verbou#2]
Setu ul listenn eus ar verboù hag a zegas beugoù d'al lec'hienn (war-sevel eo ouzhpennet e vo tamm-ha-tamm ar re-mañ):
1. aliañ.

**Comment by Wanibzh29** [comment]
Respont ar gudenn-mañ a c'hallfe bezañ lakaat un niver dirak ar verboù doublennoù met o devez meur a zoare da vezañ displeget? @tornoz

**Comment by tornoz** [comment]
Reizhet gant ar c'hommit 52449272dafca05bc9e7bc4a0f0504c52b2d9264
